---
driver:
  name: vagrant
  customize:
    cableconnected1: 'on'
  ssh:
    insert_key: false

driver_config:
  require_chef_omnibus: latest

provisioner:
  name: chef_zero
# Uncomment for debug purposes
#  log_level: debug

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.7
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[couchdb]
  - name: source
    run_list:
      - recipe[apt::default]
      - recipe[build-essential]
      - recipe[couchdb::source]     
    verifier:
      inspec_tests:
        - test/smoke/inspec
